name: "Setup .NET and Nx Environment"
description: "Sets up .NET, Node.js, installs npm dependencies, and restores NuGet packages"

runs:
  using: "composite"
  steps:
    - name: Get latest LTS .NET version
      id: dotnet-lts
      shell: bash
      run: |
        ltsVersion=$(curl -s https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json | jq -r '.["releases-index"][] | select(.["release-type"]=="lts" and .["support-phase"]=="active") | .["channel-version"]' | head -1)
        echo "version=$ltsVersion" >> $GITHUB_OUTPUT

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ steps.dotnet-lts.outputs.version }} # Needed because Nx MSBuild analyzer requires LTS Runtime and SDK
        global-json-file: global.json
        cache: true
        cache-dependency-path: "**/packages.lock.json"

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: "package.json"
        cache: "npm"

    - name: Install npm dependencies
      shell: bash
      run: npm ci

    - name: Restore NuGet dependencies
      shell: bash
      run: dotnet restore
